# File: netlify.toml

# This file tells Netlify how to build your site and where to find functions.
[build]
  # This tells Netlify where your serverless functions are located.
  functions = "netlify/functions/"
